/**
 * Mapping from MFL country names (UPPERCASE) to ISO 3166-1 alpha-2 codes.
 */
export const COUNTRY_TO_ISO: Record<string, string> = {
  AFGHANISTAN: 'AF', ALBANIA: 'AL', ALGERIA: 'DZ', ANDORRA: 'AD',
  ANGOLA: 'AO', ANTIGUA_AND_BARBUDA: 'AG', ARGENTINA: 'AR', ARMENIA: 'AM',
  AUSTRALIA: 'AU', AUSTRIA: 'AT', AZERBAIJAN: 'AZ', BAHAMAS: 'BS',
  BAHRAIN: 'BH', BANGLADESH: 'BD', BARBADOS: 'BB', BELARUS: 'BY',
  BELGIUM: 'BE', BELIZE: 'BZ', BENIN: 'BJ', BERMUDA: 'BM',
  BHUTAN: 'BT', BOLIVIA: 'BO', BOSNIA_AND_HERZEGOVINA: 'BA',
  BOTSWANA: 'BW', BRAZIL: 'BR', BRUNEI: 'BN', BULGARIA: 'BG',
  BURKINA_FASO: 'BF', BURUNDI: 'BI', CABO_VERDE: 'CV', CAMBODIA: 'KH',
  CAMEROON: 'CM', CANADA: 'CA', CAPE_VERDE: 'CV',
  CENTRAL_AFRICAN_REPUBLIC: 'CF', CHAD: 'TD', CHILE: 'CL', CHINA: 'CN',
  COLOMBIA: 'CO', COMOROS: 'KM', CONGO: 'CG',
  DEMOCRATIC_REPUBLIC_OF_THE_CONGO: 'CD', DR_CONGO: 'CD',
  COSTA_RICA: 'CR', CROATIA: 'HR', CUBA: 'CU', CURACAO: 'CW',
  CYPRUS: 'CY', CZECH_REPUBLIC: 'CZ', CZECHIA: 'CZ',
  DENMARK: 'DK', DJIBOUTI: 'DJ', DOMINICA: 'DM',
  DOMINICAN_REPUBLIC: 'DO', EAST_TIMOR: 'TL', ECUADOR: 'EC',
  EGYPT: 'EG', EL_SALVADOR: 'SV', ENGLAND: 'GB',
  EQUATORIAL_GUINEA: 'GQ', ERITREA: 'ER', ESTONIA: 'EE',
  ESWATINI: 'SZ', ETHIOPIA: 'ET', FIJI: 'FJ', FINLAND: 'FI',
  FRANCE: 'FR', FRENCH_GUIANA: 'GF', GABON: 'GA', GAMBIA: 'GM',
  GEORGIA: 'GE', GERMANY: 'DE', GHANA: 'GH', GREECE: 'GR',
  GRENADA: 'GD', GUADELOUPE: 'GP', GUAM: 'GU', GUATEMALA: 'GT',
  GUINEA: 'GN', GUINEA_BISSAU: 'GW', GUYANA: 'GY', HAITI: 'HT',
  HONDURAS: 'HN', HONG_KONG: 'HK', HUNGARY: 'HU', ICELAND: 'IS',
  INDIA: 'IN', INDONESIA: 'ID', IRAN: 'IR', IRAQ: 'IQ',
  IRELAND: 'IE', ISRAEL: 'IL', ITALY: 'IT', IVORY_COAST: 'CI',
  COTE_D_IVOIRE: 'CI', JAMAICA: 'JM', JAPAN: 'JP', JORDAN: 'JO',
  KAZAKHSTAN: 'KZ', KENYA: 'KE', KOSOVO: 'XK', KUWAIT: 'KW',
  KYRGYZSTAN: 'KG', LAOS: 'LA', LATVIA: 'LV', LEBANON: 'LB',
  LESOTHO: 'LS', LIBERIA: 'LR', LIBYA: 'LY', LIECHTENSTEIN: 'LI',
  LITHUANIA: 'LT', LUXEMBOURG: 'LU', MADAGASCAR: 'MG', MALAWI: 'MW',
  MALAYSIA: 'MY', MALDIVES: 'MV', MALI: 'ML', MALTA: 'MT',
  MARTINIQUE: 'MQ', MAURITANIA: 'MR', MAURITIUS: 'MU', MEXICO: 'MX',
  MOLDOVA: 'MD', MONACO: 'MC', MONGOLIA: 'MN', MONTENEGRO: 'ME',
  MONTSERRAT: 'MS', MOROCCO: 'MA', MOZAMBIQUE: 'MZ', MYANMAR: 'MM',
  NAMIBIA: 'NA', NEPAL: 'NP', NETHERLANDS: 'NL', NEW_CALEDONIA: 'NC',
  NEW_ZEALAND: 'NZ', NICARAGUA: 'NI', NIGER: 'NE', NIGERIA: 'NG',
  NORTH_KOREA: 'KP', NORTH_MACEDONIA: 'MK', NORTHERN_IRELAND: 'GB',
  NORWAY: 'NO', OMAN: 'OM', PAKISTAN: 'PK', PALESTINE: 'PS',
  PANAMA: 'PA', PAPUA_NEW_GUINEA: 'PG', PARAGUAY: 'PY', PERU: 'PE',
  PHILIPPINES: 'PH', POLAND: 'PL', PORTUGAL: 'PT',
  PUERTO_RICO: 'PR', QATAR: 'QA', REUNION: 'RE', ROMANIA: 'RO',
  RUSSIA: 'RU', RWANDA: 'RW', SAINT_KITTS_AND_NEVIS: 'KN',
  SAINT_LUCIA: 'LC', SAINT_VINCENT_AND_THE_GRENADINES: 'VC',
  SAMOA: 'WS', SAN_MARINO: 'SM', SAO_TOME_AND_PRINCIPE: 'ST',
  SAUDI_ARABIA: 'SA', SCOTLAND: 'GB', SENEGAL: 'SN', SERBIA: 'RS',
  SEYCHELLES: 'SC', SIERRA_LEONE: 'SL', SINGAPORE: 'SG',
  SLOVAKIA: 'SK', SLOVENIA: 'SI', SOLOMON_ISLANDS: 'SB', SOMALIA: 'SO',
  SOUTH_AFRICA: 'ZA', SOUTH_KOREA: 'KR', SOUTH_SUDAN: 'SS',
  SPAIN: 'ES', SRI_LANKA: 'LK', SUDAN: 'SD', SURINAME: 'SR',
  SWEDEN: 'SE', SWITZERLAND: 'CH', SYRIA: 'SY', TAHITI: 'PF',
  TAIWAN: 'TW', TAJIKISTAN: 'TJ', TANZANIA: 'TZ', THAILAND: 'TH',
  TOGO: 'TG', TONGA: 'TO', TRINIDAD_AND_TOBAGO: 'TT', TUNISIA: 'TN',
  TURKEY: 'TR', TURKMENISTAN: 'TM', UGANDA: 'UG', UKRAINE: 'UA',
  UNITED_ARAB_EMIRATES: 'AE', UNITED_KINGDOM: 'GB', UNITED_STATES: 'US',
  USA: 'US', URUGUAY: 'UY', UZBEKISTAN: 'UZ', VANUATU: 'VU',
  VENEZUELA: 'VE', VIETNAM: 'VN', WALES: 'GB', YEMEN: 'YE',
  ZAMBIA: 'ZM', ZIMBABWE: 'ZW',
};

/**
 * Convert MFL country name to flag emoji.
 * Falls back to the raw name if no mapping found.
 */
export function countryToFlag(name: string): { emoji: string; code: string | null } {
  // Normalize: uppercase, replace spaces/hyphens with underscores
  const key = name.toUpperCase().replace(/[\s-]+/g, '_').replace(/'/g, '_');
  const code = COUNTRY_TO_ISO[key] ?? null;
  if (!code) return { emoji: '', code: null };
  const emoji = String.fromCodePoint(
    ...code.split('').map(c => c.charCodeAt(0) + 127397)
  );
  return { emoji, code };
}
